"""added has_category

Revision ID: 83661f4fc0ea
Revises: ce2827448ff8
Create Date: 2022-07-20 22:22:27.082099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83661f4fc0ea'
down_revision = 'ce2827448ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('has_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('has_categories')
    # ### end Alembic commands ###
