"""removed constraint from category_idcolumn

Revision ID: 9da5be7b6e6e
Revises: 34d6ea88abbc
Create Date: 2022-02-17 12:03:04.196355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da5be7b6e6e'
down_revision = '34d6ea88abbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('posts', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
