"""added profile pc

Revision ID: 3c92b3e86b6a
Revises: d55dadef6a7e
Create Date: 2022-02-23 00:12:48.554895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c92b3e86b6a'
down_revision = 'd55dadef6a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_img_url')
    # ### end Alembic commands ###
