"""updated is_admin column

Revision ID: 30780a598d35
Revises: 9da5be7b6e6e
Create Date: 2022-02-18 11:47:09.885275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30780a598d35'
down_revision = '9da5be7b6e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
