"""update

Revision ID: ce2827448ff8
Revises: 81634a54c7a3
Create Date: 2022-07-20 22:19:48.429236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2827448ff8'
down_revision = '81634a54c7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    op.add_column('comments', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('comments', sa.Column('replyto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['replyto_id'], ['id'])
    op.drop_column('comments', 'content')
    op.add_column('images', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('images', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'updated_at')
    op.drop_column('images', 'created_at')
    op.add_column('comments', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'replyto_id')
    op.drop_column('comments', 'text')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
