"""empty message

Revision ID: 81634a54c7a3
Revises: 1de3ef76ed51
Create Date: 2022-07-20 21:03:22.119342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81634a54c7a3'
down_revision = '1de3ef76ed51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.String(length=255), nullable=False))
    op.drop_column('images', 'image_url')
    op.drop_constraint('posts_category_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    op.drop_column('posts', 'image_url')
    op.add_column('users', sa.Column('profile_img', sa.String(length=255), nullable=False))
    op.drop_column('users', 'profile_img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'profile_img')
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_category_id_fkey', 'posts', 'categories', ['category_id'], ['id'])
    op.add_column('images', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('images', 'url')
    # ### end Alembic commands ###
